[registry]
default = "gitea"

[registries.gitea]
index = "sparse+http://gitea:3000/api/packages/gitea/cargo/" # Sparse index
# index = "http://localhost:3000/gitea/_cargo-index.git" # Git

# [net]
# git-fetch-with-cli = true