spring.application.name=gitea_microservice
gitea.token = 431e0324fe7c6f78f30f72970662d91eedfac9c9
gitea.url = http://gitea:3000
gitea.owner = gitea
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB