spring.application.name=gitea_microservice
gitea.token = 86ff883b16662b8594e5105ddaf5015b6c70fb6a
gitea.url = http://localhost:3000
gitea.owner = gitea
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB