spring.application.name=gitea_microservice
gitea.token = bd2cf5c05ff114f9cece7ba8f9c3278f06eb95e0
gitea.url = http://gitea:3000
gitea.owner = gitea
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB